development:
 secret_key_base: ~~~~~~~~
 aws_access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
 aws_secret_access_key: <%= ENV['S3_SECRET_KEY'] %>


production:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 aws_access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
 aws_secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
